# Dockerfile для установки shadowsocks-rust
FROM alpine:3.17 as baseutil 
RUN apk add --update binutils # strip util

RUN wget -O- https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.16.2/shadowsocks-v1.16.2.x86_64-unknown-linux-musl.tar.xz | tar Jx && \
strip -s sslocal ssserver
  
FROM alpine:3.17 as base_os 
RUN addgroup -S vados && adduser -S -G vados vados      

FROM base_os

LABEL maintainer="hyperion.spb@gmail.com"
COPY --from=baseutil sslocal ssserver /usr/local/bin/
COPY docker-entrypoint.sh /usr/bin/
# взято отсюда https://github.com/shadowsocks/shadowsocks-rust/blob/master/docker/Dockerfile.v2ray
RUN cd /tmp && \
    TAG=$(wget -qO- https://api.github.com/repos/shadowsocks/v2ray-plugin/releases/latest | grep tag_name | cut -d '"' -f4) && \
    wget https://github.com/shadowsocks/v2ray-plugin/releases/download/$TAG/v2ray-plugin-linux-amd64-$TAG.tar.gz && \
	wget https://github.com/cbeuw/Cloak/releases/download/v2.7.0/ck-server-linux-amd64-v2.7.0 && \
    tar -xf *.gz && \
    rm *.gz && \
    mv v2ray* /usr/bin/v2ray-plugin && \
	mv ck-server* /usr/bin/ck-server && \
    chmod +x /usr/bin/v2ray-plugin /usr/bin/ck-server && \
    mkdir -p /etc/shadowsocks-rust

ENTRYPOINT ["docker-entrypoint.sh"]
#CMD ["ssserver", "--tcp-fast-open", "--log-without-time", "-a", "vados", "-c", "/etc/shadowsocks-rust/config.json" ]
CMD ["ssserver", "--tcp-fast-open", "--tcp-no-delay", "--log-without-time", "-c", "/etc/shadowsocks-rust/config.json" ]
#CMD ["-s", "${SERVER_ADDR}:${SERVER_PORT}", "-k", "${PASSWORD}", "-m", "${METHOD}", "-t", "${TIMEOUT}", "-d", "${DNS_ADDRS}", "--reuse-port --no-delay --fast-open", "-u"]

